apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  namespace: rabbitmq-system
  name: rabbitmq-test-ready
spec:
  replicas: 3
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi
  rabbitmq:
    additionalConfig: |
      log.console.level = info
      default_user= guest 
      default_pass = guest
      default_user_tags.administrator = true
  persistence:
    storageClassName: network-rabbitmq-storage
    storage: 5Gi
  service:
    type: LoadBalancer
  override:
    service:
      spec:
        ports:
        - port: 5672
          targetPort: 5672
        externalIPs:
        - x.y.z.1
        - x.y.z.2
        - x.y.z.3
