---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: network-rabbitmq-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: network-rabbitmq-storage
  hostPath:
    path: "/mnt/k8shared/rabbitmq"
    type: Directory
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8smaster
          - k8swnode1
          - k8swnode2
          - k8swnode3
          - k8swnode4
          - k8swnode5
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv2
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: network-rabbitmq-storage
  hostPath:
    path: "/mnt/k8shared/rabbitmq"
    type: Directory
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8smaster
          - k8swnode1
          - k8swnode2
          - k8swnode3
          - k8swnode4
          - k8swnode5
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv3
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: network-rabbitmq-storage
  hostPath:
    path: "/mnt/k8shared/rabbitmq"
    type: Directory
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8smaster
          - k8swnode1
          - k8swnode2
          - k8swnode3
          - k8swnode4
          - k8swnode5
